before:
  hooks:
builds:
  - main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
archives:
  - replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
