before:
  hooks:
builds:
  - id: windows
    main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    goos:
      - windows
  - id: notwindows
    main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - id: windows
    format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
